import { EventCategory } from "./event-category";
import { EventStatus } from "./event-status";
import { EventType } from "./event-type";

export type Event = {
  id: string;
  creatorUserId: string;
  name: string;
  slug: string;
  description: string;
  status: EventStatus;
  eventType: EventType;
  hasVoting: boolean;
  hasTicketing: boolean;
  primaryFlyerUrl: string;
  primaryFlyerKey: string;
  bannerUrl: string | null;
  bannerKey: string | null;
  nominationStartAt: Date | null;
  nominationEndAt: Date | null;
  votingStartAt: Date;
  votingEndAt: Date;
  eventStartAt: Date | null;
  eventEndAt: Date | null;
  venueName: string | null;
  venueAddress: string | null;
  ticketSalesStartAt: Date | null;
  ticketSalesEndAt: Date | null;
  contestantsCanViewOwnVotes: boolean;
  contestantsCanViewLeaderboard: boolean;
  publicCanViewLeaderboard: boolean;
  submittedAt: Date | null;
  approvedAt: Date | null;
  approvedByUserId: string | null;
  rejectedAt: Date | null;
  rejectedByUserId: string | null;
  rejectionReason: string | null;
  createdAt: Date;
  updatedAt: Date;
  categories: EventCategory[];
};
