export enum EventStatus {
  DRAFT = "DRAFT",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  REJECTED = "REJECTED",
  APPROVED = "APPROVED",
  NOMINATIONS_OPEN = "NOMINATIONS_OPEN",
  NOMINATIONS_CLOSED = "NOMINATIONS_CLOSED",
  VOTING_SCHEDULED = "VOTING_SCHEDULED",
  VOTING_LIVE = "VOTING_LIVE",
  VOTING_CLOSED = "VOTING_CLOSED",
  ARCHIVED = "ARCHIVED",
}
